# Generated by Django 4.0.4 on 2022-04-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200, null=True)),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('apellido', models.CharField(max_length=20, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
